name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make setup

  test:
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make setup

      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make setup

      - name: Run lint
        run: make lint
