name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
                node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release

  test:
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
                node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  lint:
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
                node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint
